// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdsmyhemzlaccwptgpda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impkc215aGVtemxhY2N3cHRncGRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MjQ4MDYsImV4cCI6MjA1OTAwMDgwNn0.818rYciLdkt6yVdfFyeVOOcOW2MqBMgQdODp1ZsHsHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);